---

- name: Create letsencrypt data container
  docker:
    name: letsencrypt-data
    image: quay.io/letsencrypt/letsencrypt:latest
    state: present
    command: --help

- name: Create or renew ssl certificate
  command: >
    docker run
      -it --rm --name letsencrypt
      --volumes-from=letsencrypt-data
      --net=services
      -e SERVICE_ID=letsencrypt
      quay.io/letsencrypt/letsencrypt:latest
      --standalone --text
      --server https://acme-v01.api.letsencrypt.org/directory
      --agree-dev-preview
      --agree-tos
      --renew-by-default
      --domain box.kidibox.net
      --email arnaud.rebts@gmail.com
      auth
