---

- name: Install lvm2
  pacman: name=lvm2 state=latest

- name: Create volume group
  lvg:
    vg: "{{ volume_group_name }}"
    pvs: "{{ volume_group_disk }}"

- name: Create logical volumes
  with_items: "{{ volumes }}"
  lvol:
    vg: "{{ volume_group_name }}"
    lv: "{{ item.name }}"
    size: "{{ item.size }}"

- name: Create file systems
  with_items: "{{ volumes }}"
  when: item.type is defined
  filesystem:
    dev: "/dev/{{ volume_group_name }}/{{ item.name }}"
    fstype: "{{ item.type }}"

- name: Mount logical volumes
  with_items: "{{ volumes }}"
  when: item.mount is defined
  mount:
    state: mounted
    name: "{{ item.mount }}"
    src: "/dev/{{ volume_group_name }}/{{ item.name }}"
    fstype: "{{ item.type }}"
