---

- name: Create postgres data container
  docker:
    name: kidibox-db-data
    image: busybox
    state: present
    volumes:
      - /var/lib/postgresql/data

- name: Start postgres container
  docker:
    name: kidibox-db
    image: postgres
    state: reloaded
    restart_policy: always
    volumes_from:
      - kidibox-db-data
    env:
      POSTGRES_USER: kidibox
      POSTGRES_PASSWORD: kidibox

- name: Start kidibox-api docker container
  docker:
    name: kidibox-api
    image: kidibox/kidibox-api
    state: reloaded
    restart_policy: always
    links:
      - "kidibox-db:postgres"
