---

volume_group_name: vg.data
volume_group_disk: /dev/md/data

volumes:

  - name: home
    size: 20G
    type: xfs
    mount: /home

  - name: docker.metadata
    lv: docker.metadata
    size: 10G

  - name: docker.data
    lv: docker.data
    size: 90G

  - name: docker.lib
    size: 100%FREE
    type: xfs
    mount: /var/lib/docker
