---

- name: Enable ufw service
  service: name=ufw enabled=yes

- name: Reload ufw servie
  service: name=ufw state=reloaded

- name: Restart ufw servie
  service: name=ufw state=restarted

- name: Reload ufw
  ufw: name=ufw state=reloaded
