---

- name: Create letsencrypt data only container
  command: >
    docker run -it
    --name letsencrypt-data
    --entrypoint /bin/echo
    quay.io/letsencrypt/letsencrypt
    "Data only container"
  ignore_errors: yes

- name: Create nginx data only container
  docker:
    name: nginx-data
    image: arnaudrebts/nginx-letsencrypt-proxy
    state: present

- name: Create nginx container
  docker:
    name: nginx
    image: arnaudrebts/nginx-letsencrypt-proxy
    state: reloaded
    restart_policy: always
    volumes_from:
      - letsencrypt-data
      - nginx-data
    ports:
      - "80:80"
      - "443:443"

- name: Create docker-gen container
  docker:
    name: docker-gen
    image: jwilder/docker-gen
    state: reloaded
    restart_policy: always
    volumes_from:
      - nginx-data
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: >
      --watch
      -only-exposed
      -notify-sighup nginx
      /etc/nginx/conf.d/99-vhosts.conf.tmpl
      /etc/nginx/conf.d/99-vhosts.conf

- name: Setup auto renew job
  cron:
    name: letsencrypt-renew
    special_time: weekly
    job: /usr/bin/docker run -it --rm --name letsencrypt --volumes-from letsencrypt-data --volumes-from nginx quay.io/letsencrypt/letsencrypt renew && docker kill -s SIGHUP nginx
