---

- name: Install docker
  pacman: name=docker state=latest
  notify:
    - Enable docker service
    - Reload docker service
    - Restart docker service

- name: Install docker-py
  pacman: name=python2-docker-py state=latest

- name: Creates docker configuration directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0755

- name: Copy docker configuration file
  template:
    src: docker.service.j2
    dest: /etc/systemd/system/docker.service.d/docker.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload docker service
    - Restart docker service

- name: Execute handlers
  meta: flush_handlers

- name: Create networks
  shell: "docker network ls | grep -q {{ item }} || docker network create {{ item }} || true"
  with_items:
    - services
