---

- name: Install lvm2
  pacman: name=lvm2 state=latest

- name: Create volume group
  lvg:  vg={{ lvm_vg_name }} pvs={{ lvm_vg_disk }}

- name: Create logical volumes
  lvol: vg={{ lvm_vg_name }} lv={{ item.name }} size={{ item.size }}
  with_items: "{{ lvm_logical_volumes }}"

- name: Partition logical volumes
  filesystem: dev=/dev/{{ lvm_vg_name }}/{{ item.name }} fstype={{ item.type }}
  with_items: "{{ lvm_logical_volumes_filesystems }}"

- name: Mount logical volumes
  mount: state=mounted name={{ item.mountpoint }} src=/dev/{{ lvm_vg_name }}/{{ item.lv }} fstype={{ item.type }}
  with_items: "{{ lvm_logical_volumes_mountpoints }}"
